export const POKEMON_DATA = Object.freeze([
  { name: 'Pikachu', path: 'assets/characters/Pikachu.svg', score: 50, rarity: 'epic', weight: 0.8, grip: 0.87, centerOfMassX: 0.54, centerOfMassY: 0.55 },
  { name: 'Bulbasaur', path: 'assets/characters/Bulbasaur.svg', score: 10, rarity: 'common', weight: 1.35, grip: 0.84, centerOfMassX: 0.49, centerOfMassY: 0.61 },
  { name: 'Charmander', path: 'assets/characters/Charmander.svg', score: 10, rarity: 'common', weight: 0.85, grip: 0.82, centerOfMassX: 0.51, centerOfMassY: 0.57 },
  { name: 'Vulpix', path: 'assets/characters/Vulpix.svg', score: 20, rarity: 'rare', weight: 0.8, grip: 0.78, centerOfMassX: 0.47, centerOfMassY: 0.58 },
  { name: 'Mewtwo', path: 'assets/characters/Mewtwo.svg', score: 70, rarity: 'legendary', weight: 1.1, grip: 0.62, centerOfMassX: 0.52, centerOfMassY: 0.56 },
  { name: 'Chikorita', path: 'assets/characters/Chikorita.svg', score: 10, rarity: 'common', weight: 0.85, grip: 0.84, centerOfMassX: 0.46, centerOfMassY: 0.59 },
  { name: 'Cyndaquil', path: 'assets/characters/Cyndaquil.svg', score: 10, rarity: 'common', weight: 0.78, grip: 0.86, centerOfMassX: 0.48, centerOfMassY: 0.58 },
  { name: 'Poliwag', path: 'assets/characters/Poliwag.svg', score: 10, rarity: 'common', weight: 0.72, grip: 0.92, centerOfMassX: 0.5, centerOfMassY: 0.54 },
  { name: 'Psyduck', path: 'assets/characters/Psyduck.svg', score: 10, rarity: 'common', weight: 1, grip: 0.88, centerOfMassX: 0.5, centerOfMassY: 0.58 },
  { name: 'Wartortle', path: 'assets/characters/Wartortle.svg', score: 20, rarity: 'rare', weight: 1.25, grip: 0.78, centerOfMassX: 0.5, centerOfMassY: 0.57 },
  { name: 'Arbok', path: 'assets/characters/Arbok.svg', score: -20, rarity: 'common', weight: 1.15, grip: 0.61, centerOfMassX: 0.52, centerOfMassY: 0.62 },
  { name: 'Clefairy', path: 'assets/characters/Clefairy.svg', score: 20, rarity: 'rare', weight: 0.82, grip: 0.91, centerOfMassX: 0.5, centerOfMassY: 0.55 },
  { name: 'Kingler', path: 'assets/characters/Kingler.svg', score: 20, rarity: 'rare', weight: 1.3, grip: 0.66, centerOfMassX: 0.52, centerOfMassY: 0.57 },
  { name: 'Meowth', path: 'assets/characters/Meowth.svg', score: -10, rarity: 'common', weight: 0.75, grip: 0.8, centerOfMassX: 0.48, centerOfMassY: 0.55 },
  { name: 'Ninetales', path: 'assets/characters/Ninetales.svg', score: 30, rarity: 'rare', weight: 1.2, grip: 0.68, centerOfMassX: 0.44, centerOfMassY: 0.6 },
]);
